### ISSUE TITLE
Which repositories should we build and/or inherit?

### ISSUE THREAD

**Issue by ararslan** [JuliaInterop/Roadmap.jl#2] opened 2016-07-03 01:16 UTC
Let's discuss what should be adopted from other people or organizations and what other things we should include as part of some overarching vision.

@tkelman mentioned a couple to start off the list.
- [ ] [Cxx.jl](https://github.com/Keno/Cxx.jl)
- [ ] [Clang.jl](https://github.com/ihnorton/Clang.jl)

**Comment by twadleigh** [comment] 2016-09-05 15:52
Could this be a home for [jlcall](https://github.com/twadleigh/jlcall)?

**Comment by tkelman** [comment] 2016-09-05 16:35
Sure, though it should probably have a more descriptive name.

**Comment by twadleigh** [comment] 2016-09-05 18:46
@tkelman suggestions welcome. It might also be worth considering just moving the functionality into [MATLAB.jl](https://github.com/JuliaInterop/MATLAB.jl), which was my initial intention when I put the project together.

**Comment by tkelman** [comment] 2016-09-05 19:04
something with mex and/or matlab in the name. or discuss at matlab.jl how they might be combined.

**Comment by musm** [comment] 2016-09-06 14:37
PyCall.jl and JavaCall.jl  make a lot of sense to have here.

**Comment by ararslan** [comment] 2016-09-06 16:39
PyCall.jl has been transferred to the newly founded [JuliaPy](https://github.com/JuliaPy) organization. PyJulia, currently under JuliaInterop, may be transferred to JuliaPy.

**Comment by musm** [comment] 2016-09-06 16:42
julialang site needs and update with all these various new organizations to make it clear and easy for new users. 

Perhaps also some sectioning to separate closely related organizations from each other

**Comment by ararslan** [comment] 2016-09-06 16:55
If you're referring to http://julialang.org/community/, I agree it could use some updating, as things have been moving around a lot.

**Comment by musm** [comment] 2016-09-06 18:07
yeah

**Comment by ararslan** [comment] 2016-09-06 18:31
You could open ~~an issue~~ a PR at https://github.com/JuliaLang/julialang.github.com

**Comment by tkelman** [comment] 2016-09-06 18:32
If you open an issue it'll get closed as a duplicate of https://github.com/JuliaLang/julialang.github.com/issues/383. Open a PR.

**Comment by musm** [comment] 2021-04-28 12:54
closing as we can take any further discussion related to this on discourse or slack

**Closed as completed by musm** 2021-04-28 12:54 UTC
